//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ADUserDetail", Namespace="http://tempuri.org/")]
    public partial class ADUserDetail : object
    {
        
        private string SicilNoField;
        
        private string PersonelIdField;
        
        private string DepartmentField;
        
        private string FirstNameField;
        
        private string MiddleNameField;
        
        private string LastNameField;
        
        private string LoginNameField;
        
        private string LoginNameWithDomainField;
        
        private string StreetAddressField;
        
        private string CityField;
        
        private string StateField;
        
        private string PostalCodeField;
        
        private string CountryField;
        
        private string HomePhoneField;
        
        private string ExtensionField;
        
        private string MobileField;
        
        private string FaxField;
        
        private string EmailAddressField;
        
        private string TitleField;
        
        private string CompanyField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SicilNo
        {
            get
            {
                return this.SicilNoField;
            }
            set
            {
                this.SicilNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string PersonelId
        {
            get
            {
                return this.PersonelIdField;
            }
            set
            {
                this.PersonelIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Department
        {
            get
            {
                return this.DepartmentField;
            }
            set
            {
                this.DepartmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string MiddleName
        {
            get
            {
                return this.MiddleNameField;
            }
            set
            {
                this.MiddleNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string LoginName
        {
            get
            {
                return this.LoginNameField;
            }
            set
            {
                this.LoginNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string LoginNameWithDomain
        {
            get
            {
                return this.LoginNameWithDomainField;
            }
            set
            {
                this.LoginNameWithDomainField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string StreetAddress
        {
            get
            {
                return this.StreetAddressField;
            }
            set
            {
                this.StreetAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string PostalCode
        {
            get
            {
                return this.PostalCodeField;
            }
            set
            {
                this.PostalCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                this.CountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string HomePhone
        {
            get
            {
                return this.HomePhoneField;
            }
            set
            {
                this.HomePhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string Extension
        {
            get
            {
                return this.ExtensionField;
            }
            set
            {
                this.ExtensionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string Mobile
        {
            get
            {
                return this.MobileField;
            }
            set
            {
                this.MobileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string Fax
        {
            get
            {
                return this.FaxField;
            }
            set
            {
                this.FaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string EmailAddress
        {
            get
            {
                return this.EmailAddressField;
            }
            set
            {
                this.EmailAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string Company
        {
            get
            {
                return this.CompanyField;
            }
            set
            {
                this.CompanyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserProcessing", Namespace="http://tempuri.org/")]
    public partial class UserProcessing : object
    {
        
        private string KulIdField;
        
        private string SicilNoField;
        
        private string UserNameField;
        
        private string MessageField;
        
        private int StatusField;
        
        private string MailField;
        
        private string BolgeIdField;
        
        private string SurnameField;
        
        private string NameField;
        
        private ServiceReference1.UserRoles[] RollerField;
        
        private ServiceReference1.UserYetki[] YetkilerField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string KulId
        {
            get
            {
                return this.KulIdField;
            }
            set
            {
                this.KulIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SicilNo
        {
            get
            {
                return this.SicilNoField;
            }
            set
            {
                this.SicilNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Mail
        {
            get
            {
                return this.MailField;
            }
            set
            {
                this.MailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string BolgeId
        {
            get
            {
                return this.BolgeIdField;
            }
            set
            {
                this.BolgeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Surname
        {
            get
            {
                return this.SurnameField;
            }
            set
            {
                this.SurnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public ServiceReference1.UserRoles[] Roller
        {
            get
            {
                return this.RollerField;
            }
            set
            {
                this.RollerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public ServiceReference1.UserYetki[] Yetkiler
        {
            get
            {
                return this.YetkilerField;
            }
            set
            {
                this.YetkilerField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserRoles", Namespace="http://tempuri.org/")]
    public partial class UserRoles : object
    {
        
        private int RolIdField;
        
        private string RolNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RolId
        {
            get
            {
                return this.RolIdField;
            }
            set
            {
                this.RolIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RolName
        {
            get
            {
                return this.RolNameField;
            }
            set
            {
                this.RolNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserYetki", Namespace="http://tempuri.org/")]
    public partial class UserYetki : object
    {
        
        private int YetkiIdField;
        
        private string YetkiNameField;
        
        private int AccessLevelField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int YetkiId
        {
            get
            {
                return this.YetkiIdField;
            }
            set
            {
                this.YetkiIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string YetkiName
        {
            get
            {
                return this.YetkiNameField;
            }
            set
            {
                this.YetkiNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int AccessLevel
        {
            get
            {
                return this.AccessLevelField;
            }
            set
            {
                this.AccessLevelField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserKeys", Namespace="http://tempuri.org/")]
    public partial class UserKeys : object
    {
        
        private int KeyIdField;
        
        private string KeyNameField;
        
        private ServiceReference1.KeyValues[] ValuesField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int KeyId
        {
            get
            {
                return this.KeyIdField;
            }
            set
            {
                this.KeyIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string KeyName
        {
            get
            {
                return this.KeyNameField;
            }
            set
            {
                this.KeyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ServiceReference1.KeyValues[] Values
        {
            get
            {
                return this.ValuesField;
            }
            set
            {
                this.ValuesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeyValues", Namespace="http://tempuri.org/")]
    public partial class KeyValues : object
    {
        
        private int ValueIdField;
        
        private string ValueNameField;
        
        private string ValueValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ValueId
        {
            get
            {
                return this.ValueIdField;
            }
            set
            {
                this.ValueIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ValueName
        {
            get
            {
                return this.ValueNameField;
            }
            set
            {
                this.ValueNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ValueValue
        {
            get
            {
                return this.ValueValueField;
            }
            set
            {
                this.ValueValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.LdapWebServicesSoap")]
    public interface LdapWebServicesSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidateLdapUser", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.ValidateLdapUserResponse> ValidateLdapUserAsync(ServiceReference1.ValidateLdapUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnXml", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.ReturnXmlResponse> ReturnXmlAsync(ServiceReference1.ReturnXmlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUsersFromFirstName", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetUsersFromFirstNameResponse> GetUsersFromFirstNameAsync(ServiceReference1.GetUsersFromFirstNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserDetailsByLoginName", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetUserDetailsByLoginNameResponse> GetUserDetailsByLoginNameAsync(ServiceReference1.GetUserDetailsByLoginNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserInformation", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetUserInformationResponse> GetUserInformationAsync(ServiceReference1.GetUserInformationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserKeys", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetUserKeysResponse> GetUserKeysAsync(ServiceReference1.GetUserKeysRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateLdapUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateLdapUser", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ValidateLdapUserRequestBody Body;
        
        public ValidateLdapUserRequest()
        {
        }
        
        public ValidateLdapUserRequest(ServiceReference1.ValidateLdapUserRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidateLdapUserRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public ValidateLdapUserRequestBody()
        {
        }
        
        public ValidateLdapUserRequestBody(string userName, string password)
        {
            this.userName = userName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateLdapUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateLdapUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ValidateLdapUserResponseBody Body;
        
        public ValidateLdapUserResponse()
        {
        }
        
        public ValidateLdapUserResponse(ServiceReference1.ValidateLdapUserResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidateLdapUserResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ValidateLdapUserResult;
        
        public ValidateLdapUserResponseBody()
        {
        }
        
        public ValidateLdapUserResponseBody(bool ValidateLdapUserResult)
        {
            this.ValidateLdapUserResult = ValidateLdapUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReturnXmlRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReturnXml", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ReturnXmlRequestBody Body;
        
        public ReturnXmlRequest()
        {
        }
        
        public ReturnXmlRequest(ServiceReference1.ReturnXmlRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ReturnXmlRequestBody
    {
        
        public ReturnXmlRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReturnXmlResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReturnXmlResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ReturnXmlResponseBody Body;
        
        public ReturnXmlResponse()
        {
        }
        
        public ReturnXmlResponse(ServiceReference1.ReturnXmlResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReturnXmlResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement ReturnXmlResult;
        
        public ReturnXmlResponseBody()
        {
        }
        
        public ReturnXmlResponseBody(System.Xml.XmlElement ReturnXmlResult)
        {
            this.ReturnXmlResult = ReturnXmlResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsersFromFirstNameRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsersFromFirstName", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetUsersFromFirstNameRequestBody Body;
        
        public GetUsersFromFirstNameRequest()
        {
        }
        
        public GetUsersFromFirstNameRequest(ServiceReference1.GetUsersFromFirstNameRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUsersFromFirstNameRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string firstName;
        
        public GetUsersFromFirstNameRequestBody()
        {
        }
        
        public GetUsersFromFirstNameRequestBody(string firstName)
        {
            this.firstName = firstName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsersFromFirstNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsersFromFirstNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetUsersFromFirstNameResponseBody Body;
        
        public GetUsersFromFirstNameResponse()
        {
        }
        
        public GetUsersFromFirstNameResponse(ServiceReference1.GetUsersFromFirstNameResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUsersFromFirstNameResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.ADUserDetail[] GetUsersFromFirstNameResult;
        
        public GetUsersFromFirstNameResponseBody()
        {
        }
        
        public GetUsersFromFirstNameResponseBody(ServiceReference1.ADUserDetail[] GetUsersFromFirstNameResult)
        {
            this.GetUsersFromFirstNameResult = GetUsersFromFirstNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserDetailsByLoginNameRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserDetailsByLoginName", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetUserDetailsByLoginNameRequestBody Body;
        
        public GetUserDetailsByLoginNameRequest()
        {
        }
        
        public GetUserDetailsByLoginNameRequest(ServiceReference1.GetUserDetailsByLoginNameRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserDetailsByLoginNameRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loginName;
        
        public GetUserDetailsByLoginNameRequestBody()
        {
        }
        
        public GetUserDetailsByLoginNameRequestBody(string loginName)
        {
            this.loginName = loginName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserDetailsByLoginNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserDetailsByLoginNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetUserDetailsByLoginNameResponseBody Body;
        
        public GetUserDetailsByLoginNameResponse()
        {
        }
        
        public GetUserDetailsByLoginNameResponse(ServiceReference1.GetUserDetailsByLoginNameResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserDetailsByLoginNameResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.ADUserDetail GetUserDetailsByLoginNameResult;
        
        public GetUserDetailsByLoginNameResponseBody()
        {
        }
        
        public GetUserDetailsByLoginNameResponseBody(ServiceReference1.ADUserDetail GetUserDetailsByLoginNameResult)
        {
            this.GetUserDetailsByLoginNameResult = GetUserDetailsByLoginNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserInformationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserInformation", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetUserInformationRequestBody Body;
        
        public GetUserInformationRequest()
        {
        }
        
        public GetUserInformationRequest(ServiceReference1.GetUserInformationRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserInformationRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int appId;
        
        public GetUserInformationRequestBody()
        {
        }
        
        public GetUserInformationRequestBody(string userName, string password, int appId)
        {
            this.userName = userName;
            this.password = password;
            this.appId = appId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserInformationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserInformationResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetUserInformationResponseBody Body;
        
        public GetUserInformationResponse()
        {
        }
        
        public GetUserInformationResponse(ServiceReference1.GetUserInformationResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserInformationResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.UserProcessing GetUserInformationResult;
        
        public GetUserInformationResponseBody()
        {
        }
        
        public GetUserInformationResponseBody(ServiceReference1.UserProcessing GetUserInformationResult)
        {
            this.GetUserInformationResult = GetUserInformationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserKeysRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserKeys", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetUserKeysRequestBody Body;
        
        public GetUserKeysRequest()
        {
        }
        
        public GetUserKeysRequest(ServiceReference1.GetUserKeysRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserKeysRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        public GetUserKeysRequestBody()
        {
        }
        
        public GetUserKeysRequestBody(string userName)
        {
            this.userName = userName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserKeysResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserKeysResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetUserKeysResponseBody Body;
        
        public GetUserKeysResponse()
        {
        }
        
        public GetUserKeysResponse(ServiceReference1.GetUserKeysResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserKeysResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.UserKeys[] GetUserKeysResult;
        
        public GetUserKeysResponseBody()
        {
        }
        
        public GetUserKeysResponseBody(ServiceReference1.UserKeys[] GetUserKeysResult)
        {
            this.GetUserKeysResult = GetUserKeysResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface LdapWebServicesSoapChannel : ServiceReference1.LdapWebServicesSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class LdapWebServicesSoapClient : System.ServiceModel.ClientBase<ServiceReference1.LdapWebServicesSoap>, ServiceReference1.LdapWebServicesSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public LdapWebServicesSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(LdapWebServicesSoapClient.GetBindingForEndpoint(endpointConfiguration), LdapWebServicesSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LdapWebServicesSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(LdapWebServicesSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LdapWebServicesSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(LdapWebServicesSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LdapWebServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.ValidateLdapUserResponse> ServiceReference1.LdapWebServicesSoap.ValidateLdapUserAsync(ServiceReference1.ValidateLdapUserRequest request)
        {
            return base.Channel.ValidateLdapUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ValidateLdapUserResponse> ValidateLdapUserAsync(string userName, string password)
        {
            ServiceReference1.ValidateLdapUserRequest inValue = new ServiceReference1.ValidateLdapUserRequest();
            inValue.Body = new ServiceReference1.ValidateLdapUserRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            return ((ServiceReference1.LdapWebServicesSoap)(this)).ValidateLdapUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.ReturnXmlResponse> ServiceReference1.LdapWebServicesSoap.ReturnXmlAsync(ServiceReference1.ReturnXmlRequest request)
        {
            return base.Channel.ReturnXmlAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ReturnXmlResponse> ReturnXmlAsync()
        {
            ServiceReference1.ReturnXmlRequest inValue = new ServiceReference1.ReturnXmlRequest();
            inValue.Body = new ServiceReference1.ReturnXmlRequestBody();
            return ((ServiceReference1.LdapWebServicesSoap)(this)).ReturnXmlAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetUsersFromFirstNameResponse> ServiceReference1.LdapWebServicesSoap.GetUsersFromFirstNameAsync(ServiceReference1.GetUsersFromFirstNameRequest request)
        {
            return base.Channel.GetUsersFromFirstNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetUsersFromFirstNameResponse> GetUsersFromFirstNameAsync(string firstName)
        {
            ServiceReference1.GetUsersFromFirstNameRequest inValue = new ServiceReference1.GetUsersFromFirstNameRequest();
            inValue.Body = new ServiceReference1.GetUsersFromFirstNameRequestBody();
            inValue.Body.firstName = firstName;
            return ((ServiceReference1.LdapWebServicesSoap)(this)).GetUsersFromFirstNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetUserDetailsByLoginNameResponse> ServiceReference1.LdapWebServicesSoap.GetUserDetailsByLoginNameAsync(ServiceReference1.GetUserDetailsByLoginNameRequest request)
        {
            return base.Channel.GetUserDetailsByLoginNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetUserDetailsByLoginNameResponse> GetUserDetailsByLoginNameAsync(string loginName)
        {
            ServiceReference1.GetUserDetailsByLoginNameRequest inValue = new ServiceReference1.GetUserDetailsByLoginNameRequest();
            inValue.Body = new ServiceReference1.GetUserDetailsByLoginNameRequestBody();
            inValue.Body.loginName = loginName;
            return ((ServiceReference1.LdapWebServicesSoap)(this)).GetUserDetailsByLoginNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetUserInformationResponse> ServiceReference1.LdapWebServicesSoap.GetUserInformationAsync(ServiceReference1.GetUserInformationRequest request)
        {
            return base.Channel.GetUserInformationAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetUserInformationResponse> GetUserInformationAsync(string userName, string password, int appId)
        {
            ServiceReference1.GetUserInformationRequest inValue = new ServiceReference1.GetUserInformationRequest();
            inValue.Body = new ServiceReference1.GetUserInformationRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.appId = appId;
            return ((ServiceReference1.LdapWebServicesSoap)(this)).GetUserInformationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetUserKeysResponse> ServiceReference1.LdapWebServicesSoap.GetUserKeysAsync(ServiceReference1.GetUserKeysRequest request)
        {
            return base.Channel.GetUserKeysAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetUserKeysResponse> GetUserKeysAsync(string userName)
        {
            ServiceReference1.GetUserKeysRequest inValue = new ServiceReference1.GetUserKeysRequest();
            inValue.Body = new ServiceReference1.GetUserKeysRequestBody();
            inValue.Body.userName = userName;
            return ((ServiceReference1.LdapWebServicesSoap)(this)).GetUserKeysAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LdapWebServicesSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.LdapWebServicesSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LdapWebServicesSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://172.22.23.33/yetkiService/Services/LdapWebServices.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.LdapWebServicesSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://172.22.23.33/yetkiService/Services/LdapWebServices.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            LdapWebServicesSoap,
            
            LdapWebServicesSoap12,
        }
    }
}
